Change Marcels photo and main cower
TP2023-T24-PEACE/timova-stranka pull request #9
Opened 2023-10-26 14:23 UTC by MarosLuk

2023-10-26 16:20 UTC, Matt1s commented
Prosim zmen tu fotku alebo z nej aspon sprav zelenu a acceptnem to

2023-10-26 16:21 UTC, Matt1s requested changes
Change cover photo

2023-10-29 22:03 UTC, MarosLuk commented
Titulovy obrazok som nechal teda ten fade co tam pridal matej. Ostatne doplenenie a uprava vystupu zapisnic

2023-10-29 22:04 UTC, MarosLuk commented
> Prosim zmen tu fotku alebo z nej aspon sprav zelenu a acceptnem to

Titulovy obrazok som nechal teda ten fade co tam pridal matej. Ostatne doplenenie a uprava vystupu zapisnic

2023-10-29 23:48 UTC, merged